### ISSUE TITLE
 undeclared identifier 'i'

### ISSUE THREAD

**Issue by rendi88** [akihisaArchieSakai/URP-UniVrm#5]
Hi..
Im new to use your shader and I like it and i thought this package is best so far..
im found an issue
Im using Unity 2020.3.5f1 and add your package and build it and theres error like this

> Shader error in 'VRM10/MToon10': undeclared identifier 'i' at UniVrm/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_forward_fragment.hlsl(48) (on d3d11)
> 
> Compiling Vertex program with DIRECTIONAL FOG_EXP2
> Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING UNITY_PASS_FORWARDBASE
> Disabled keywords: _ALPHATEST_ON _ALPHABLEND_ON _NORMALMAP _MTOON_EMISSIVEMAP _MTOON_RIMMAP _MTOON_PARAMETERMAP FOG_LINEAR FOG_EXP INSTANCING_ON LIGHTPROBE_SH SHADOWS_SHADOWMASK SHADOWS_SCREEN LIGHTMAP_SHADOW_MIXING UNITY_NO_DXT5nm UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_VIRTUAL_TEXTURING UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_ASTC_NORMALMAP_ENCODING SHADER_API_GLES30

Could you give me info how to solve it ? I like this shader
Thank you

**Comment by akihisaArchieSakai** [comment]
Thanks for the issue!
MToon10 in VRM10 is not used in this package, so if you delete the VRM10 folder, this error will be resolved.
(I did not delete it after importing UniVrm. Sorry.)


I will update the package later so that it will work fine.

Thank you so much for letting me know.

**Comment by akihisaArchieSakai** [comment]
Hey there!

As I said before, I think your project will build well if you remove the VRM10 folder, but if you are replacing the package, please use the following unitypackage file.

https://github.com/akihisaArchieSakai/URP-UniVrm/releases/tag/ver-1.0.3

I have also successfully built the project on 2020.3.17f1.

**Comment by rendi88** [comment]
thankyou... its means alot for me
btw im make a little modification to make alpha transparency going smooth
https://ibb.co/D7gL1Bf
maybe it can improve your shader

**Comment by akihisaArchieSakai** [comment]
Nice!

If you fork this repository and send me a pull request, I'll merge it.
